# Generated by Django 5.2.4 on 2025-11-10 23:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('ADOPTANTE', 'Adoptante'), ('REFUGIO', 'Refugio')], default='ADOPTANTE', max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('activo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
                'ordering': ['tipo_animal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Animal',
                'verbose_name_plural': 'Tipos de Animales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilAdoptante',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_adoptante', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('tipo_vivienda', models.CharField(blank=True, choices=[('CASA', 'Casa'), ('DEPARTAMENTO', 'Departamento'), ('PARCELA', 'Parcela')], max_length=50)),
                ('tiene_patio', models.BooleanField(default=False)),
                ('es_propietario', models.BooleanField(default=False)),
                ('experiencia_previa', models.BooleanField(default=False)),
                ('tiene_mascotas', models.BooleanField(default=False)),
                ('cantidad_mascotas', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Perfil Adoptante',
                'verbose_name_plural': 'Perfiles Adoptantes',
            },
        ),
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_refugio', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('anio_fundacion', models.IntegerField(blank=True, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('documento_verificacion', models.FileField(blank=True, null=True, upload_to='documentos_refugios/')),
                ('verificado', models.BooleanField(default=False)),
                ('logo', models.TextField(blank=True, null=True)),
                ('portada', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=250)),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('horario_atencion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Refugio',
                'verbose_name_plural': 'Refugios',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('MACHO', 'Macho'), ('HEMBRA', 'Hembra')], max_length=10)),
                ('edad', models.CharField(choices=[('CACHORRO', 'Cachorro (0-1 año)'), ('JOVEN', 'Joven (1-3 años)'), ('ADULTO', 'Adulto (3-8 años)'), ('SENIOR', 'Senior (8 años o más)')], max_length=20)),
                ('descripcion', models.TextField()),
                ('tamano', models.CharField(blank=True, choices=[('PEQUENO', 'Pequeño (0-10 kg)'), ('MEDIANO', 'Mediano (10-25 kg)'), ('GRANDE', 'Grande (25-45 kg)'), ('GIGANTE', 'Gigante (45+ kg)')], help_text='Tamaño aproximado del animal', max_length=10)),
                ('color', models.CharField(blank=True, help_text='Color predominante del pelaje', max_length=100)),
                ('esterilizado', models.BooleanField(default=False)),
                ('desparasitado', models.BooleanField(default=False)),
                ('microchip', models.BooleanField(default=False)),
                ('vacunas', models.JSONField(blank=True, default=dict, help_text='DEPRECADO: Usar VacunaMascota en su lugar')),
                ('necesidades_especiales', models.TextField(blank=True)),
                ('nivel_energia', models.CharField(blank=True, choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], help_text='Nivel de actividad física requerida', max_length=10)),
                ('nivel_cuidado', models.CharField(blank=True, choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], help_text='Nivel de cuidados necesarios', max_length=10)),
                ('apto_ninos', models.BooleanField(default=False, help_text='Apto para convivir con niños')),
                ('apto_apartamento', models.BooleanField(default=False, help_text='Se adapta bien a espacios pequeños')),
                ('sociable_perros', models.BooleanField(default=False, help_text='Se lleva bien con otros perros')),
                ('sociable_gatos', models.BooleanField(default=False, help_text='Se lleva bien con gatos')),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('foto_2', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('foto_3', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('ADOPTADO', 'Adoptado'), ('BORRADOR', 'Borrador')], default='DISPONIBLE', max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='core.raza')),
                ('tipo_animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mascotas', to='core.tipoanimal')),
                ('refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='core.refugio')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('mensaje', models.TextField()),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='core.mascota')),
            ],
            options={
                'verbose_name': 'Solicitud de Adopción',
                'verbose_name_plural': 'Solicitudes de Adopción',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_adopcion', models.DateField()),
                ('fecha_inicio_seguimiento', models.DateField(blank=True, null=True)),
                ('fecha_fin_seguimiento', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ALERTA', 'Alerta'), ('COMPLETADA', 'Completada'), ('DEVUELTA', 'Devuelta'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('contrato_firmado', models.BooleanField(default=False)),
                ('documento_contrato', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('strikes', models.PositiveSmallIntegerField(default=0)),
                ('max_strikes', models.PositiveSmallIntegerField(default=3)),
                ('visitas_planificadas', models.PositiveSmallIntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adopcion', to='core.solicitudadopcion')),
            ],
            options={
                'verbose_name': 'Adopción',
                'verbose_name_plural': 'Adopciones',
                'ordering': ['-fecha_adopcion'],
            },
        ),
        migrations.AddField(
            model_name='raza',
            name='tipo_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razas', to='core.tipoanimal'),
        ),
        migrations.CreateModel(
            name='TipoVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('obligatoria', models.BooleanField(default=False, help_text='Indica si es una vacuna obligatoria')),
                ('activo', models.BooleanField(default=True)),
                ('tipo_animal', models.ForeignKey(help_text='Tipo de animal al que aplica esta vacuna', on_delete=django.db.models.deletion.CASCADE, related_name='vacunas_disponibles', to='core.tipoanimal')),
            ],
            options={
                'verbose_name': 'Tipo de Vacuna',
                'verbose_name_plural': 'Tipos de Vacunas',
                'ordering': ['tipo_animal', 'nombre'],
                'unique_together': {('nombre', 'tipo_animal')},
            },
        ),
        migrations.CreateModel(
            name='TwoFactorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('bloqueado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_2fa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código 2FA',
                'verbose_name_plural': 'Códigos 2FA',
            },
        ),
        migrations.CreateModel(
            name='VisitaSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_visita', models.PositiveSmallIntegerField()),
                ('fecha_programada', models.DateField()),
                ('fecha_realizada', models.DateField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EXITOSO', 'Exitoso'), ('REQUIERE_ATENCION', 'Requiere Atención'), ('PROBLEMATICO', 'Problemático'), ('NO_REALIZADA', 'No Realizada')], default='PENDIENTE', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('puntuacion', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('estado_salud', models.CharField(blank=True, choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('PREOCUPANTE', 'Preocupante')], max_length=20, null=True)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('adopcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='core.adopcion')),
                ('realizada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visita de Seguimiento',
                'verbose_name_plural': 'Visitas de Seguimiento',
                'ordering': ['adopcion', 'numero_visita'],
                'unique_together': {('adopcion', 'numero_visita')},
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(choices=[('SALUD', 'Salud'), ('NUTRICION', 'Nutrición'), ('COMPORTAMIENTO', 'Comportamiento'), ('ADIESTRAMIENTO', 'Adiestramiento'), ('HIGIENE', 'Higiene'), ('GENERAL', 'General')], max_length=20)),
                ('imagen', models.TextField(blank=True)),
                ('publicado', models.BooleanField(default=True)),
                ('tipo_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips', to='core.tipoanimal')),
                ('refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='core.refugio')),
            ],
            options={
                'verbose_name': 'Tip',
                'verbose_name_plural': 'Tips',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RedSocialRefugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram')], max_length=20)),
                ('url', models.URLField(max_length=250)),
                ('refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociales', to='core.refugio')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
        migrations.CreateModel(
            name='ContactoRefugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('TELEFONO', 'Teléfono'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SITIO_WEB', 'Sitio Web')], max_length=20)),
                ('valor', models.CharField(blank=True, max_length=250)),
                ('principal', models.BooleanField(default=False)),
                ('refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='core.refugio')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_kpi', models.CharField(choices=[('PARTICIPANTES', 'Número de Participantes'), ('ADOPCIONES', 'Número de Adopciones'), ('DONACIONES', 'Monto de Donaciones'), ('VISITAS', 'Número de Visitas')], max_length=20)),
                ('meta_kpi', models.IntegerField(help_text='Meta a alcanzar')),
                ('valor_actual_kpi', models.IntegerField(default=0, help_text='Valor actual alcanzado')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('PAUSADA', 'Pausada'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanas', to='core.refugio')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacionCampana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='core.campana')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_campanas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participación en Campaña',
                'verbose_name_plural': 'Participaciones en Campañas',
                'unique_together': {('campana', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='VacunaMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField(help_text='Fecha en que se aplicó la vacuna')),
                ('fecha_proxima', models.DateField(blank=True, help_text='Fecha de la próxima dosis o refuerzo', null=True)),
                ('lote', models.CharField(blank=True, help_text='Número de lote de la vacuna', max_length=50)),
                ('veterinario', models.CharField(blank=True, help_text='Nombre del veterinario que aplicó la vacuna', max_length=200)),
                ('notas', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas_aplicadas', to='core.mascota')),
                ('tipo_vacuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='core.tipovacuna')),
            ],
            options={
                'verbose_name': 'Vacuna de Mascota',
                'verbose_name_plural': 'Vacunas de Mascotas',
                'ordering': ['-fecha_aplicacion'],
                'indexes': [models.Index(fields=['mascota', '-fecha_aplicacion'], name='core_vacuna_mascota_e80484_idx'), models.Index(fields=['fecha_proxima'], name='core_vacuna_fecha_p_0bac4c_idx')],
                'unique_together': {('mascota', 'tipo_vacuna', 'fecha_aplicacion')},
            },
        ),
        migrations.CreateModel(
            name='FotoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='visitas/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.visitaseguimiento')),
            ],
            options={
                'verbose_name': 'Foto de Visita',
                'verbose_name_plural': 'Fotos de Visitas',
                'ordering': ['visita', 'orden'],
                'unique_together': {('visita', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='ResenaRefugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(help_text='Calificación de 1 a 5 estrellas')),
                ('comentario', models.TextField(blank=True)),
                ('respondido', models.BooleanField(default=False)),
                ('respuesta', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_refugios', to=settings.AUTH_USER_MODEL)),
                ('refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='core.refugio')),
            ],
            options={
                'verbose_name': 'Reseña de Refugio',
                'verbose_name_plural': 'Reseñas de Refugios',
                'ordering': ['-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('calificacion__gte', 1), ('calificacion__lte', 5)), name='calificacion_valida')],
                'unique_together': {('refugio', 'usuario')},
            },
        ),
        migrations.AddIndex(
            model_name='mascota',
            index=models.Index(fields=['estado', 'tipo_animal'], name='core_mascot_estado_aa3fac_idx'),
        ),
        migrations.AddIndex(
            model_name='mascota',
            index=models.Index(fields=['refugio', 'estado'], name='core_mascot_refugio_bccefc_idx'),
        ),
        migrations.AddIndex(
            model_name='mascota',
            index=models.Index(fields=['tamano', 'nivel_energia'], name='core_mascot_tamano_d5d6e9_idx'),
        ),
        migrations.AddIndex(
            model_name='mascota',
            index=models.Index(fields=['-fecha_ingreso'], name='core_mascot_fecha_i_7e0b5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='mascota',
            constraint=models.CheckConstraint(condition=models.Q(('nombre', ''), _negated=True), name='mascota_nombre_no_vacio'),
        ),
        migrations.AddConstraint(
            model_name='mascota',
            constraint=models.CheckConstraint(condition=models.Q(('descripcion', ''), _negated=True), name='mascota_descripcion_no_vacia'),
        ),
    ]
