# Generated by Django 5.2.4 on 2025-11-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adopcion',
            index=models.Index(fields=['estado'], name='core_adopci_estado_71a6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='adopcion',
            index=models.Index(fields=['fecha_adopcion'], name='core_adopci_fecha_a_09dbd9_idx'),
        ),
        migrations.AddIndex(
            model_name='adopcion',
            index=models.Index(fields=['solicitud'], name='core_adopci_solicit_8e23d0_idx'),
        ),
        migrations.AddIndex(
            model_name='fotovisita',
            index=models.Index(fields=['visita', 'orden'], name='core_fotovi_visita__6933e1_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudadopcion',
            index=models.Index(fields=['estado'], name='core_solici_estado_700b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudadopcion',
            index=models.Index(fields=['adoptante'], name='core_solici_adoptan_a23de0_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudadopcion',
            index=models.Index(fields=['mascota'], name='core_solici_mascota_b77977_idx'),
        ),
        migrations.AddIndex(
            model_name='visitaseguimiento',
            index=models.Index(fields=['adopcion', 'numero_visita'], name='core_visita_adopcio_0b9806_idx'),
        ),
        migrations.AddIndex(
            model_name='visitaseguimiento',
            index=models.Index(fields=['resultado'], name='core_visita_resulta_9f6939_idx'),
        ),
        migrations.AddIndex(
            model_name='visitaseguimiento',
            index=models.Index(fields=['fecha_programada'], name='core_visita_fecha_p_0673e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='adopcion',
            constraint=models.CheckConstraint(condition=models.Q(('strikes__gte', 0)), name='adopcion_strikes_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='adopcion',
            constraint=models.CheckConstraint(condition=models.Q(('max_strikes__lte', 3)), name='adopcion_max_strikes_lte_3'),
        ),
        migrations.AddConstraint(
            model_name='adopcion',
            constraint=models.CheckConstraint(condition=models.Q(('strikes__lte', models.F('max_strikes'))), name='adopcion_strikes_lte_max'),
        ),
        migrations.AddConstraint(
            model_name='adopcion',
            constraint=models.CheckConstraint(condition=models.Q(('visitas_planificadas__gte', 0)), name='adopcion_visitas_planificadas_gte_0'),
        ),
    ]
