# Generated by Django 5.2.4 on 2025-11-18 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adopcion_core_adopci_estado_71a6d9_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoVoluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_evento', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('ubicacion', models.CharField(max_length=300)),
                ('cupos_disponibles', models.PositiveIntegerField(default=10)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=20)),
                ('requisitos', models.TextField(blank=True, help_text='Requisitos para participar en el voluntariado')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='voluntariados/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_voluntariado', to='core.refugio')),
            ],
            options={
                'verbose_name': 'Evento de Voluntariado',
                'verbose_name_plural': 'Eventos de Voluntariado',
                'ordering': ['-fecha_evento', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionVoluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('CANCELADO', 'Cancelado'), ('ASISTIO', 'Asistió'), ('NO_ASISTIO', 'No Asistió')], default='INSCRITO', max_length=20)),
                ('comentario', models.TextField(blank=True, help_text='Comentario o motivación del voluntario')),
                ('notas_refugio', models.TextField(blank=True, help_text='Notas del refugio sobre el voluntario')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.eventovoluntariado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_voluntariado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción Voluntariado',
                'verbose_name_plural': 'Inscripciones Voluntariado',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
        migrations.AddIndex(
            model_name='eventovoluntariado',
            index=models.Index(fields=['fecha_evento'], name='core_evento_fecha_e_64611c_idx'),
        ),
        migrations.AddIndex(
            model_name='eventovoluntariado',
            index=models.Index(fields=['estado'], name='core_evento_estado_655759_idx'),
        ),
        migrations.AddIndex(
            model_name='eventovoluntariado',
            index=models.Index(fields=['refugio', 'estado'], name='core_evento_refugio_d992df_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcionvoluntariado',
            index=models.Index(fields=['evento', 'estado'], name='core_inscri_evento__d6ed98_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcionvoluntariado',
            index=models.Index(fields=['usuario', 'estado'], name='core_inscri_usuario_9dd03e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionvoluntariado',
            unique_together={('evento', 'usuario')},
        ),
    ]
