# Generated by Django 5.2.4 on 2025-11-18 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eventovoluntariado_inscripcionvoluntariado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participacioncampana',
            options={'ordering': ['-created_at'], 'verbose_name': 'Participación en Campaña', 'verbose_name_plural': 'Participaciones en Campañas'},
        ),
        migrations.AlterModelOptions(
            name='resenarefugio',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reseña de Refugio', 'verbose_name_plural': 'Reseñas de Refugios'},
        ),
        migrations.AlterModelOptions(
            name='solicitudadopcion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitud de Adopción', 'verbose_name_plural': 'Solicitudes de Adopción'},
        ),
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tip', 'verbose_name_plural': 'Tips'},
        ),
        migrations.AddField(
            model_name='participacioncampana',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resenarefugio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resenarefugio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='solicitudadopcion',
            index=models.Index(fields=['-created_at'], name='core_solici_created_081cda_idx'),
        ),
    ]
