# Generated by Django 5.2.4 on 2025-11-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_participacioncampana_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaseguimiento',
            name='peso_actual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg (máximo 200)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='visitaseguimiento',
            name='puntuacion',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Puntuación de 1 a 5', null=True),
        ),
        migrations.AddIndex(
            model_name='campana',
            index=models.Index(fields=['estado'], name='core_campan_estado_4ea9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='campana',
            index=models.Index(fields=['refugio', 'estado'], name='core_campan_refugio_68fc49_idx'),
        ),
        migrations.AddIndex(
            model_name='campana',
            index=models.Index(fields=['fecha_inicio'], name='core_campan_fecha_i_fb6030_idx'),
        ),
        migrations.AddIndex(
            model_name='campana',
            index=models.Index(fields=['fecha_fin'], name='core_campan_fecha_f_3185c2_idx'),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['categoria'], name='core_tip_categor_d46b71_idx'),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['publicado'], name='core_tip_publica_6de36c_idx'),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['refugio', 'publicado'], name='core_tip_refugio_ea1828_idx'),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['tipo_animal'], name='core_tip_tipo_an_7a9c1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='campana',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='campana_fechas_validas'),
        ),
        migrations.AddConstraint(
            model_name='campana',
            constraint=models.CheckConstraint(condition=models.Q(('meta_kpi__gt', 0)), name='campana_meta_kpi_positiva'),
        ),
        migrations.AddConstraint(
            model_name='campana',
            constraint=models.CheckConstraint(condition=models.Q(('valor_actual_kpi__gte', 0)), name='campana_valor_kpi_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='perfiladoptante',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_mascotas__gte', 0)), name='adoptante_cantidad_mascotas_positiva'),
        ),
        migrations.AddConstraint(
            model_name='refugio',
            constraint=models.CheckConstraint(condition=models.Q(('anio_fundacion__isnull', True), models.Q(('anio_fundacion__gte', 1900), ('anio_fundacion__lte', 2100)), _connector='OR'), name='refugio_anio_fundacion_valido'),
        ),
        migrations.AddConstraint(
            model_name='refugio',
            constraint=models.CheckConstraint(condition=models.Q(('capacidad__isnull', True), ('capacidad__gte', 0), _connector='OR'), name='refugio_capacidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='visitaseguimiento',
            constraint=models.CheckConstraint(condition=models.Q(('puntuacion__isnull', True), models.Q(('puntuacion__gte', 1), ('puntuacion__lte', 5)), _connector='OR'), name='visita_puntuacion_rango_valido'),
        ),
        migrations.AddConstraint(
            model_name='visitaseguimiento',
            constraint=models.CheckConstraint(condition=models.Q(('peso_actual__isnull', True), models.Q(('peso_actual__gt', 0), ('peso_actual__lte', 200)), _connector='OR'), name='visita_peso_actual_valido'),
        ),
    ]
