# Generated by Django 5.2.4 on 2025-11-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_visitaseguimiento_peso_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='campanas/'),
        ),
        migrations.AlterField(
            model_name='refugio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='refugios/logos/'),
        ),
        migrations.AlterField(
            model_name='refugio',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='refugios/portadas/'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tips/'),
        ),
    ]
