# Generated by Django 5.2.4 on 2025-11-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_campana_imagen_alter_refugio_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='vacunas',
        ),
    ]
