# Generated by Django 5.2.4 on 2025-11-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_mascota_vacunas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactorcode',
            name='code',
        ),
        migrations.AddField(
            model_name='twofactorcode',
            name='code_hash',
            field=models.CharField(default='', help_text='Hash SHA256 del código', max_length=128),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='twofactorcode',
            constraint=models.CheckConstraint(condition=models.Q(('intentos__gte', 0), ('intentos__lte', 3)), name='twofactor_intentos_validos'),
        ),
    ]
