# Generated by Django 5.2.4 on 2025-11-19 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_twofactorcode_code_twofactorcode_code_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('CONTRATOS', 'Contratos'), ('POLITICAS', 'Políticas'), ('FORMULARIOS', 'Formularios'), ('CERTIFICADOS', 'Certificados'), ('LEGALES', 'Legales'), ('OTROS', 'Otros')], max_length=20)),
                ('tipo_archivo', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'Word'), ('XLSX', 'Excel'), ('TXT', 'Texto')], max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('BORRADOR', 'Borrador'), ('ARCHIVADO', 'Archivado')], default='ACTIVO', max_length=20)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('tamano', models.PositiveIntegerField(help_text='Tamaño del archivo en bytes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('descargas', models.PositiveIntegerField(default=0)),
                ('usos', models.PositiveIntegerField(default=0)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_creados', to=settings.AUTH_USER_MODEL)),
                ('refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.refugio')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_modificacion'],
                'indexes': [models.Index(fields=['refugio', 'categoria'], name='core_docume_refugio_b4343a_idx'), models.Index(fields=['estado', 'fecha_modificacion'], name='core_docume_estado_d88ea2_idx')],
            },
        ),
    ]
