# Generated by Django 5.2.4 on 2025-11-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacioncampana',
            name='asistio',
            field=models.BooleanField(default=False, help_text='Indica si el usuario asistió a la campaña'),
        ),
    ]
