# Generated by Django 5.2.4 on 2025-11-19 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_participacioncampana_asistio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='core.mascota')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mascota Favorita',
                'verbose_name_plural': 'Mascotas Favoritas',
                'ordering': ['-fecha_agregado'],
                'indexes': [models.Index(fields=['usuario', 'fecha_agregado'], name='core_mascot_usuario_921c09_idx')],
                'unique_together': {('usuario', 'mascota')},
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SOLICITUD_NUEVA', 'Nueva Solicitud de Adopción'), ('SOLICITUD_APROBADA', 'Solicitud Aprobada'), ('SOLICITUD_RECHAZADA', 'Solicitud Rechazada'), ('VISITA_PROGRAMADA', 'Visita de Seguimiento Programada'), ('CAMPANA_NUEVA', 'Nueva Campaña Disponible'), ('TIP_NUEVO', 'Nuevo Tip Publicado'), ('VOLUNTARIADO_NUEVO', 'Nuevo Evento de Voluntariado'), ('MENSAJE_GENERAL', 'Mensaje General')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, help_text='URL de redirección al hacer clic', max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='core_notifi_usuario_c30a38_idx'), models.Index(fields=['fecha_creacion'], name='core_notifi_fecha_c_43566a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TipFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='core.tip')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tip Favorito',
                'verbose_name_plural': 'Tips Favoritos',
                'ordering': ['-fecha_agregado'],
                'indexes': [models.Index(fields=['usuario', 'fecha_agregado'], name='core_tipfav_usuario_1754b5_idx')],
                'unique_together': {('usuario', 'tip')},
            },
        ),
    ]
