# Generated by Django 5.2.4 on 2025-11-19 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_mascotafavorita_notificacion_tipfavorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('ALIMENTO', 'Alimento'), ('MEDICAMENTO', 'Medicamento'), ('EQUIPO', 'Equipo'), ('HIGIENE', 'Higiene'), ('JUGUETE', 'Juguete'), ('OTRO', 'Otro')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('unidad', models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('litro', 'Litro'), ('caja', 'Caja'), ('bolsa', 'Bolsa')], max_length=20)),
                ('stock_minimo', models.PositiveIntegerField(default=1, help_text='Cantidad mínima antes de alertar por bajo stock')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Precio en pesos chilenos (CLP)', max_digits=10)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('fecha_ultima_compra', models.DateField(blank=True, help_text='Fecha de la última compra o reposición', null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento del producto (si aplica)', null=True)),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación física del item (ej: Bodega A, Estante 3)', max_length=200)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el item')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='core.refugio')),
            ],
            options={
                'verbose_name': 'Item de Inventario',
                'verbose_name_plural': 'Items de Inventario',
                'ordering': ['-fecha_actualizacion', 'nombre'],
                'indexes': [models.Index(fields=['refugio', 'categoria'], name='core_itemin_refugio_a60091_idx'), models.Index(fields=['refugio', 'cantidad'], name='core_itemin_refugio_03465d_idx'), models.Index(fields=['fecha_vencimiento'], name='core_itemin_fecha_v_e47753_idx'), models.Index(fields=['-fecha_actualizacion'], name='core_itemin_fecha_a_858d95_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='inventario_cantidad_no_negativa'), models.CheckConstraint(condition=models.Q(('stock_minimo__gte', 0)), name='inventario_stock_minimo_no_negativo'), models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='inventario_precio_no_negativo')],
            },
        ),
    ]
