# Generated by Django 5.2.4 on 2025-11-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_iteminventario'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mascota',
            new_name='core_mascot_estado_b9ffc6_idx',
            old_name='core_mascot_estado_aa3fac_idx',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(blank=True, default=1, help_text='Ejemplo: Labrador, Siamés, Mestizo, etc.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo_animal',
            field=models.CharField(help_text='Ejemplo: Perro, Gato, Conejo, etc.', max_length=100),
        ),
    ]
