# Generated by Django 5.2.4 on 2025-11-20 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_core_mascot_estado_aa3fac_idx_core_mascot_estado_b9ffc6_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mascota',
            new_name='core_mascot_estado_aa3fac_idx',
            old_name='core_mascot_estado_b9ffc6_idx',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='core.raza'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mascotas', to='core.tipoanimal'),
        ),
    ]
